# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Interpreted, interactive, object-oriented programming language
brew "python@3.14"
cask "font-jetbrains-mono-nerd-font"
vscode "christian-kohler.path-intellisense"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.python-environment-manager"
vscode "donjayamanne.python-extension-pack"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "gruntfuggly.todo-tree"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpp-devtools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "njpwerner.autodocstring"
vscode "usernamehw.errorlens"
